# Generated by Django 4.0.4 on 2022-04-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rollno', models.IntegerField()),
                ('class_std', models.IntegerField()),
                ('telugu', models.IntegerField()),
                ('english', models.IntegerField()),
                ('social', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
